version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  reviewers:
  - canyener
  assignees:
  - canyener
  ignore:
  - dependency-name: MSTest.TestFramework
    versions:
    - 2.2.2
